language: node_js

node_js:
  - '8'

notifications:
  email: false

cache:
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn ci-check

after_success:
  - yarn semantic-release

before_deploy:
  - yarn build

deploy:
  skip_cleanup: true
  provider: cloudfoundry
  username: apikey
  password: $CLOUD_API_KEY
  api: https://api.ng.bluemix.net
  organization: carbon-design-system
  space: production
  on:
    branch: master
